apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-store-deployment
  namespace: backends
  labels: 
    app: backend-store
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: backend-store
  template:
    metadata:
      labels:
        app: backend-store
    spec:
      containers:
      - name: backend-store
        image:  chaphe/backend-store-image:1.1
        ports:
        - containerPort: 8082
        env:
        env: 
        - name: MYSQL_DB_HOST
          value: mysql-service.databases.svc.cluster.local
        - name: MYSQL_DB_PORT
          value: "3306"  
        - name: MYSQL_DB_USERNAME
          value: root
        - name: MYSQL_DB_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-store-service
spec:
  type: NodePort
  selector:
    app: backend-store
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30100
